#
# Deploy with:
# helm repo add mycharts https://benc-uk.github.io/helm-charts
# helm install armview mycharts/webapp -f app.yaml
#

image:
  tag: 0.0.3
  repository: ghcr.io/benc-uk/armview-web
  pullPolicy: Always

service:
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 80Mi
  requests:
    cpu: 200m
    memory: 60Mi

ingress:
  enabled: true
  host: armview.kube.benco.io
  # annotations:
  #   kubernetes.io/ingress.class: addon-http-application-routing
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: true
    secretName: kube-benco-io-cert
